#!/bin/sh

VAULT_PATH=/opt/maidsafe/vault

if [ ! -f $VAULT_PATH/vault-manager ] ; then
  echo "vault manager executable is missing in $VAULT_PATH" >&2
  exit 1
fi
if [ ! -f $VAULT_PATH/vault_manager_daemoniser ] ; then
  echo "vault manager daemoniser is missing in $VAULT_PATH" >&2
  exit 1
fi
ln -s $VAULT_PATH/vault-manager /usr/bin/maidsafe_vault_manager
ln -s $VAULT_PATH/vault_manager_daemoniser /etc/init.d/maidsafe_vault_manager
/usr/sbin/update-rc.d maidsafe_vault_manager defaults
/etc/init.d/maidsafe_vault_manager start

exit 0
